### ISSUE TITLE
Feature to stop scanning when server is unresponsive or got 403 more than 3 time 

### ISSUE THREAD

**Issue by Nishantbhagat57** [r0oth3x49/ghauri#100]
**Is your feature request related to a problem? Please describe.**
When 403 (Forbidden), ghauri asks for user input (y/n) even when I have used --batch argument.

My command:
```ghauri -r req.txt --timeout 10 --threads 40 --level 3 --batch```

Ghauri Output:
![Screenshot 2023-09-15 222001](https://github.com/r0oth3x49/ghauri/assets/64642374/d82bdab1-bc1f-47cf-8eba-ad6d668ef3d5)

**Expected behavior**
```--batch             Never ask for user input, use the default behavior```

My command:
```ghauri -r req.txt --timeout 10 --threads 40 --level 3 --batch```

**Describe the solution you'd like**

As I said in https://github.com/r0oth3x49/ghauri/issues/98 @r0oth3x49 Well then there should be a default behavior for that 403 Forbidden, that's "N" coz as you said "hammering it won't help" and you haven't added that default behavior yet.

Actually it's breaking my automation workflow where I am using 8 axiom instances to parallely scan urls using ghauri...If at some point the server responds with 403, then the whole automation will break as ghauri will be expecting an input (y/n) whereas it should have taken the default input as N itself and have stopped further scanning as I have already added --batch argument :/

Well if you don't want to change anything then still you can add a ***feature*** to stop scanning when server is unresponsive or got 403 more than 3 time which can be used with --batch like this:

```ghauri -r req.txt --level 3 --stop_when_unresponsive --batch```

**Describe alternatives you've considered**
There is no alternative available as ghauri would always expect me to enter y or n

**Comment by Nishantbhagat57** [comment]
ping @r0oth3x49

**Comment by r0oth3x49** [comment]
Will add a mechanism for this

**Comment by Nishantbhagat57** [comment]
@r0oth3x49 Thank you :) Will you add this in upcoming days? it's a small update but it's crucial for my workflow and really thanks for this amazing tool :)

**Comment by r0oth3x49** [comment]
In next update --batch should work for 403 case too
