### ISSUE TITLE
On 1.2.4 Time-based payloads wont work

### ISSUE THREAD

**Issue by mastercho** [r0oth3x49/ghauri#101]
**Describe the bug**
Coming from https://github.com/r0oth3x49/ghauri/issues/96  i did update version today and no more can detect specific time-based websites on which manually can confirm its there. It's still works on 1.2.3 but in this version we got the issue https://github.com/r0oth3x49/ghauri/issues/96 which i reported.  You got website in email but seems you forgot, will remind you

**To Reproduce**
`ghauri -u "http://***.bg/load/*" -D bu*** --tables --skip-urlencode
`

**Expected behavior**
To match time-based and start tables retrieval 

**Screenshots**
![Screenshot](https://ruri.please-fuck.me/6eWER9dQN.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Ghauri version which is causing the error (should be latest) 1.2.4
 - Type of SQL injection which cause the error: time
 - Phase where error occur: detection

**Additional context**
Will reply on email to remind you @r0oth3x49

**Comment by r0oth3x49** [comment]
I check the target manually within burp there is no sleep its a false positive case. Skip urlencode issue will be resolved in next update but the target you provided in email is either fixed or a false positive.

**Comment by mastercho** [comment]
> I check the target manually within burp there is no sleep its a false positive case. Skip urlencode issue will be resolved in next update but the target you provided in email is either fixed or a false positive.

I don't know how you check but i can retrieve manually database name, version 1.2.3 also gets database name and its valid sleeps 6 if i set 6. Only reason i can think is you just dont wanna work on this issue
