### ISSUE TITLE
Add more table extraction payloads on time-based

### ISSUE THREAD

**Issue by mastercho** [r0oth3x49/ghauri#102]
**Is your feature request related to a problem? Please describe.**
We need more table name extraction payloads in Ghauri as you know its fails mainly at that stage.

**Describe the solution you'd like**
To retrieve table names after getting table numbers.

**Comment by r0oth3x49** [comment]
Will think about it in future releases I don't have any plan to add more if you want you can fork it and play around with your copy of ghauri.
