### ISSUE TITLE
-m and --batch options for list of urls and automatic reply with Y on Ghauri

### ISSUE THREAD

**Issue by 1br00** [r0oth3x49/ghauri#106]
Hello, Ghauri is going very well these days, nice work!
I have one suggestion, can you please add -m for providing a list of urls, and --batch for autoreply with Y 
Please, it woud be great to have these options in Ghauri.

**Comment by r0oth3x49** [comment]
Already requested features so closing this and the other one with dup

**Comment by skalvin** [comment]
can we know please when the -m option when will be added and release?
