### ISSUE TITLE
Ignore Code Feature Request

### ISSUE THREAD

**Issue by sabir789** [r0oth3x49/ghauri#112]
Assalam O Walikum Sir,

Sir if you add the ignore code feature its will be good in sqlmap the ignore code feature is looking like this --ignore-code=<401>
In ghauri when we give him a request file then ghauri check first if the site allow us or not if the status code of the site is 401 ghauri say the request session is expired i face this issue multiple time so Sir plz add this feature.

I have a sql injection vulnerable site that have bug bounty but sqlmap fail and ghauri is good but in this case i fail. and also ghauri.

Thanks SIr.  plz add this feature.

**Comment by r0oth3x49** [comment]
That is specific to authenticated injection. If your session is expired then it is useless to hammer server with payloads that is why I added this 401 session check if session doesn't exists update the file with new session and ghauri will resume

**Comment by sabir789** [comment]
Sir i am talking about the "Authorization: Basic admin:admin" header.
the first admin is username and the second is password.
The problem is that the username and password is base64 encoded : is also


Sir me bat kr rha ho un site ke jo direct pop-up krta ha aik box aur
credentials mangta ha sqlmap me o feature b nai ha
usko krny kelyi suffix and prefix ka use krky hoskta ha lkn ghauri me pr
base64 encoding wala tamper b nai ha aise waja sy o waly site scan nai ho
parhe ha.

aur is me session nai hota agr apka login theek howa tb session server
generate krta ha aur header me add hojataa ha.

Sir me Screen Shot add krdonga Plz agr is pe kaam hojaye to Best rhega.

aur sir plz agr Graphql kelyi b koyi Option add kry to best hoga.

Aik chota sa Request.

Thank you Sir.

**Comment by r0oth3x49** [comment]
you can simply base64 encode and pass the header to ghauri with --header="Authorization: basic BASE64ENCODESTRING" it should work with that. for GraphQL i will check. i don't have any specific lab setup for that which i need to and i don't have enough time due to other projects for setting up a lab. if you have one share it on my email and i will try things out on that.
email: `nasir251292@gmail.com`

**Comment by amohar** [comment]
Hello, we encountered this message `[WARNING] It seems the session got expired, update the session and re-run` too. In our case, we were testing POST log-in functionality, where we used `--data` to set up the POST username and password variables. We defaulted them to "test" and "test" (mimicking a currently unknown user name and password - this was on OWASP Juice Shop, which we know is vulnerable), and we were running it on the login form unauthenticated. Our aim was to have Ghauri test the username and password POST entries for injection. Ghauri tried the nonexistent username and password as a sanity check (I guess) and got 401 unauthenticated responses, which was expected from our end, but Ghauri reacted as if the session had expired.

Could you please let us know if this is expected and if we approached this in the wrong way? Thanks!

**Comment by sabir789** [comment]
Same Issue in phase multiple time. Previously i request that if you add a
feature like --ignore-code so it will be good so the ghauri will not
closing and ghauri will be process like for other status code.
