### ISSUE TITLE
Timebased Database retrieval use in Between

### ISSUE THREAD

**Issue by mastercho** [r0oth3x49/ghauri#113]
**Describe the bug**
When message   `[WARNING] it appears that the character '>' is filtered by the back-end server. ghauri will based data retrieval on BETWEEN operator` appears Ghauri gets database name double letter like must be

`planetba_01`

but ghauri retrieve database name like `ppllaanneettbbaa__0011`

Or like in screenshot here 

![rxSCwNO3Yz](https://github.com/r0oth3x49/ghauri/assets/10222100/00ae2f68-21a0-46bf-adb1-cd0603aab15b)

retreived `nnttoobbss` instead `ntobs`

`--skip-urlencode` doesn't help

**To Reproduce** 
`ghauri -r run.txt --level=3 --dbs
`
**Expected behavior**
To retrieve correct database name

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Ghauri version: 1.2.9
 - Type of SQL injection which cause the error: time
 - Phase where error occur: db(s)

**Comment by r0oth3x49** [comment]
this is not a bug it happens due to internet issue or target response time you can increase --time-sec value to above 10 or 20 default is 5 for more accuracy.

**Comment by mastercho** [comment]
> this is not a bug it happens due to internet issue or target response time you can increase --time-sec value to above 10 or 20 default is 5 for more accuracy.

Thats not the case, i tried already that, in sqlmap works on time-sec 2 not need even 5
