### ISSUE TITLE
ghauri asks for user input (y/n) even when I have used --batch argument

### ISSUE THREAD

**Issue by Nishantbhagat57** [r0oth3x49/ghauri#116]
**Describe the bug**
@r0oth3x49  ghauri asks for user input (y/n) even when I have used --batch argument

My command:
```ghauri -r req.txt --dbs --confirm --timeout 10 --threads 30 --level 3 --flush-session --fresh-queries --batch```

Ghauri Output:
![Screenshot 2023-12-03 165805](https://github.com/r0oth3x49/ghauri/assets/64642374/41f6a759-64b3-4a3d-84fd-9e6f9a359ac2)
![Screenshot 2023-12-03 165719](https://github.com/r0oth3x49/ghauri/assets/64642374/d5e52881-e53a-4baf-9ffe-04cef958211c)

**Expected behavior**
```--batch             Never ask for user input, use the default behavior```

There should be a default behavior for everything when using ```--batch```

It's breaking my automation workflow. If at some point the ghauri asks for any input, then the whole automation will break as ghauri will be expecting an input (y/n) whereas it should have taken the default input as N or Y itself as I have already added --batch argument.

Related issue that was fixed earlier: https://github.com/r0oth3x49/ghauri/issues/100

**Desktop:**
 - OS: [Debian]
 - Ghauri version: latest 1.2.9
 - Type of SQL injection which cause the error: [Default]

**Comment by Nishantbhagat57** [comment]
@r0oth3x49 ping

**Comment by r0oth3x49** [comment]
It will only ask in case of cookies.

**Comment by r0oth3x49** [comment]
Will check and add batch

**Comment by 0xhunster** [comment]
Sometimes batch do not work.
