### ISSUE TITLE
Query table name error

### ISSUE THREAD

**Issue by 867810770** [r0oth3x49/ghauri#117]
When using --tables to query the database table name, an error message is reported: [WARNING] it was not possible to extract query output length for the SQL query provided.
![1701873340729](https://github.com/r0oth3x49/ghauri/assets/42743655/4bb10321-ad7d-44ff-8566-a6784a29b8e1)

**Comment by r0oth3x49** [comment]
In this case you need to proxy requests through burp and find out manually the working query for. The above warning simply shows  that ghauri don't have query to get table name length or the queries being used either blocked or not working so try out manually.
