### ISSUE TITLE
Now wotking with root 

### ISSUE THREAD

**Issue by imran-niaz** [r0oth3x49/ghauri#12]
/usr/lib/python3/dist-packages/setuptools/dist.py:507: UserWarning: The version specified ('1.0#stable') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
UNKNOWN

**Comment by r0oth3x49** [comment]
You are installing an old version

**Comment by imran-niaz** [comment]
then where is new

**Comment by r0oth3x49** [comment]
Can you pleas explain your system environment? The program is pretty straight to install

**Comment by r0oth3x49** [comment]
i have tested it with root and normal user both it works fine, please follow the issue reporting template so that i can easily reproduce the issue.
