### ISSUE TITLE
ghauri asks for user input (y/n) even when I have used --batch argument [303 Redirect]

### ISSUE THREAD

**Issue by Nishantbhagat57** [r0oth3x49/ghauri#122]
**Describe the bug**
@r0oth3x49  ghauri asks for user input (y/n) even when I have used --batch argument

My command:
```ghauri -r req.txt --dbs --confirm --timeout 10 --threads 40 --level 3 --flush-session --fresh-queries --batch```

Ghauri Output:
![Screenshot 2023-12-31 204725](https://github.com/r0oth3x49/ghauri/assets/64642374/3820dc1a-804f-481c-8082-73682ad00b83)

**Expected behavior**
```--batch             Never ask for user input, use the default behavior```

There should be a default behavior for everything when using ```--batch```

It's breaking my automation workflow. If at some point the ghauri asks for any input, then the whole automation will break as ghauri will be expecting an input (y/n) whereas it should have taken the default input as N or Y itself as I have already added --batch argument.

Related issues that were fixed earlier:
https://github.com/r0oth3x49/ghauri/issues/100
https://github.com/r0oth3x49/ghauri/issues/116

**Desktop:**
 - OS: [Debian]
 - Ghauri version: latest 1.3
 - Type of SQL injection which cause the error: [Default]

**Comment by Nishantbhagat57** [comment]
@r0oth3x49 ping

**Comment by r0oth3x49** [comment]
already fixed in upcoming updates. i am a bit busy with other projects.. on this one i only work in my free time so sorry for the delays.

**Comment by Nishantbhagat57** [comment]
> already fixed in upcoming updates. i am a bit busy with other projects.. on this one i only work in my free time so sorry for the delays.

@r0oth3x49 Any plans to release the update?
