### ISSUE TITLE
Is this a FALSE POSITIVE ?

### ISSUE THREAD

**Issue by shivpratapsingh111** [r0oth3x49/ghauri#126]
I am able to get sql-shell (using --sql-shell) but I am not able to retrieve anything, 
Even i am not able to get the hostname or db name 
It says:

```
Parameter: #1* (URI)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: https://redacted.redacted.com/account/profile/32571' AND 05855=5855 OR '04586'='4586

[01:19:44] [INFO] testing Oracle
[01:19:46] [INFO] confirming Oracle
[01:19:46] [INFO] the back-end DBMS is Oracle
[01:19:46] [INFO] fetching hostname
[01:19:49] [INFO] retrieving the length of query output
[01:19:53] [INFO] retrieved: : 
[01:19:53] [WARNING] it was not possible to extract query output length for the SQL query provided.
```
But When I tried to get the name of currently logged user using the **sql-shell** I get this:

![image](https://github.com/r0oth3x49/ghauri/assets/106021529/e001f550-6881-4a1e-a443-38f3aabdfa8f)

# I don't know if it is a false positive or what, Can you please clarify.

**Comment by r0oth3x49** [comment]
it can be you should always verify manually the boolean/time based cases.

**Comment by mastercho** [comment]
sql-shell not working in Ghauri expect if is not error based sqli, on timebased and blind will act like your screenshot
