### ISSUE TITLE
target.txt keep only the command of the last scanned url for a subdomain

### ISSUE THREAD

**Issue by DylanTiger** [r0oth3x49/ghauri#138]
Scanning multiple urls for the same subdomain, in case injections points are detected on more urls, the file target.txt contains only the ghauri command related to one url.

1. scan a url for a subdomain where ghauri can find an injection point in GET parameter (POST may have the bug too)
2. scan another url for the same domain, ghauri should find another injection point in GET parameter 
3. check file $HOME/.ghauri/<subdomain>/target.txt. You'll have only one command.

**Expected behavior**
Having the commands related to all urls scanned

**Desktop (please complete the following information):**
 - OS: Debian and Kali
 - Ghauri version which is causing the error (should be latest): 1.3
 - Type of SQL injection which cause the error: [e.g. boolean/time/error based]
 - Phase where error occur: data

**Additional context**
I did a bash script with a loop to scan multiple urls with ghauri. Using files saved in the .ghauri/<sudomain> folder, reviewing the results is not easy.
In log, we don't have the url. In session.lite, there's not a column with the url with parameters, we should assemble it using the endpoint, he subdomain and the parameters columns and the target.txt has the mentioned bug.

**Comment by r0oth3x49** [comment]
will check this thanks for the issue.

**Comment by r0oth3x49** [comment]
@DylanTiger sorry for the very delayed response but i have checked it now and it is intended response this is how it should work, the targer.txt just saves the current command ran not the history for it even you can try sqlmap it does the same if you try it the same way you suggested in the issue.
