### ISSUE TITLE
Bug or maybe not

### ISSUE THREAD

**Issue by hussamtamaro** [r0oth3x49/ghauri#141]
(0,CONCAT_WS(0x28,0x7e,(SELECT COUNT(*)FROM(INFORMATION_SCHEMA.TABLES)WHERE(TABLE_SCHEMA IN(0x65786368616e6765))),0x7e))

Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)

why in error based 
why it get tables from information schema ? if it is blocked why i don't get tables direct

**Comment by r0oth3x49** [comment]
you better google things related to SQL injection that should help you more.
