### ISSUE TITLE
Can't read tables!

### ISSUE THREAD

**Issue by cod3r-dev** [r0oth3x49/ghauri#142]
I get current database and user but i can't enumerate the 182 tables...

Maybe firewall ? Any solution?

<img width="878" alt="image" src="https://github.com/r0oth3x49/ghauri/assets/9705923/599ccd40-fef8-46ef-bd46-dabf29f7ecf1">

**Comment by terwb** [comment]
I have the same thing

**Comment by r0oth3x49** [comment]
yes it could be a firewall you can proxy the traffic through burp to see whats going on and try manually, this response is intended when Ghauri find some sort of blockage during payloads it says this.
