### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by 2028383846** [r0oth3x49/ghauri#143]
ModuleNotFoundError: No module named 'ghauri.common'; 'ghauri' is not a package:

![微信截图_20240527174720](https://github.com/r0oth3x49/ghauri/assets/52805428/be07c5aa-16c3-4fc5-84f2-e5e24bc86862)

**Comment by Bornunique911** [comment]
I would suggest following the installation guideline once which you can check out by following this link : https://github.com/r0oth3x49/ghauri/issues/119#issuecomment-1873049386
