### ISSUE TITLE
Conversion failed when converting the varchar value 'r0oth3x49~12~END' to data type int.

### ISSUE THREAD

**Issue by dinkadereje** [r0oth3x49/ghauri#145]
**Describe the bug**
[13:51:14] [WARNING] invalid character detected, retrying..
[13:51:14] [WARNING] invalid character detected, retrying..
[13:51:15] [WARNING] invalid character detected, retrying..
[13:51:15] [WARNING] invalid character detected, retrying..
[13:51:16] [WARNING] invalid character detected, retrying..
[13:51:16] [WARNING] invalid character detected, retrying..

**To Reproduce**
1. clone the latest version
2. installed using following command ```....```
3. Run the following command  tried to dump the tables and the Error Happened then tried to capture the traffic using burp then found this Error
**Conversion failed when converting the varchar value 'r0oth3x49~12~END' to data type int.**
5. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/r0oth3x49/ghauri/assets/24679180/1dd4dde6-5a90-4089-8c09-6a2eaaf3c2fb)
![image](https://github.com/r0oth3x49/ghauri/assets/24679180/e140b64f-5039-4485-946c-e3380c61c49d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Ghauri version {1.3.2}
 - Type of SQL injection which cause the error:Time Based
 - Phase where error occur: [e.g. detection-T {tableName} --dump

**Additional context**

**Comment by r0oth3x49** [comment]
i might need more information such as target etc to reproduce and fix, if you are okay with sharing you can email me on: `nasir251292@gmail.com`
