### ISSUE TITLE
Content-Type header not support

### ISSUE THREAD

**Issue by passwa11** [r0oth3x49/ghauri#147]
**Describe the bug**

**To Reproduce**
1. clone the latest version
2. installed using following command ```....```
3. Run the following command ```...```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu/Windows/MacOS]
 - Ghauri version which is causing the error (should be latest) [e.g. 1.0.1]
 - Type of SQL injection which cause the error: [e.g. boolean/time/error based]
 - Phase where error occur: [e.g. detection/(db(s)/banner/user/table/column/data) exfiltration phase]

**Additional context**

**Comment by r0oth3x49** [comment]
would you mind providing proper details instead of just creating issue with default template contents if not i will close this issue.

**Comment by r0oth3x49** [comment]
you can directly save http request to file and use `-r` switch instead of providing everything in command line that way ghauri will process the request more like a browser. what you can do is simply save this soup/xml request to file after intercepting in burp and that should work fine.
