### ISSUE TITLE
[20:05:37] [CRITICAL] target URL is not responding..

### ISSUE THREAD

**Issue by xzkazah** [r0oth3x49/ghauri#158]
Ghauri is a good tool, unfortunately I'm encountering this problem on the database of a site I'm trying to dump.
The site is functional, but after a while Ghauri disconnects and leaves the message
[20:05:37] [CRITICAL] target URL is not responding...

Nothing is logged of course, is there any way to fix/bypass this? 

![34](https://github.com/r0oth3x49/ghauri/assets/170562894/568f042f-685b-4d0a-825f-12af18985101)

**Comment by anchoret-x** [comment]
How is this problem solved
