### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 4Orion4** [r0oth3x49/ghauri#162]
`Usage:
  C:\Users\johnm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Users\johnm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Users\johnm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Users\johnm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Users\johnm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install [options] <archive url/path> ...

-e option requires 1 argument`

occurs when I run python3 -m pip install -e

Additionally, the other command throws the same error that is depicted in the installation guide. 

I did already install the requirements.txt

**Comment by 4Orion4** [comment]
wait is it linux only

**Comment by r0oth3x49** [comment]
No it's not. It's cross platform tool. You can follow installation guideline on readme
