### ISSUE TITLE
 line 26, in <module> |  ModuleNotFoundError: No module named 'ghauri.common'; 'ghauri' is not a package

### ISSUE THREAD

**Issue by a1k-ghaz1** [r0oth3x49/ghauri#165]
┌──(ma㉿Windows11)-[~]
└─$ sudo git clone https://github.com/r0oth3x49/ghauri.git
Cloning into 'ghauri'...
remote: Enumerating objects: 1039, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 1039 (delta 125), reused 128 (delta 113), pack-reused 787
Receiving objects: 100% (1039/1039), 362.58 KiB | 338.00 KiB/s, done.
Resolving deltas: 100% (772/772), done.

┌──(ma㉿Windows11)-[~]
└─$ cd ghauri

┌──(ma㉿Windows11)-[~/ghauri]
└─$ ls
ghauri  LICENSE  README.md  requirements.txt  setup.py

┌──(ma㉿Windows11)-[~/ghauri]
└─$ pwd
/home/ma/ghauri

┌──(ma㉿Windows11)-[~/ghauri]
└─$ sudo python3 -m pip install --upgrade -r requirements.txt
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/ratelimit-2.2.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/dicttoxml-1.7.16-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/requests_file-2.1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/idna-3.7-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/tldextract-5.1.2-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/certifi-2024.7.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/chardet-5.2.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/filelock-3.15.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/charset_normalizer-3.3.2-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/arjun-2.2.6-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: tldextract in /usr/local/lib/python3.11/dist-packages/tldextract-5.1.2-py3.11.egg (from -r requirements.txt (line 1)) (5.1.2)
Requirement already satisfied: colorama in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (2.31.0)
Collecting requests (from -r requirements.txt (line 3))
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: chardet in /usr/local/lib/python3.11/dist-packages/chardet-5.2.0-py3.11.egg (from -r requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages/idna-3.7-py3.11.egg (from tldextract->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.11/dist-packages/requests_file-2.1.0-py3.11.egg (from tldextract->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.11/dist-packages/filelock-3.15.4-py3.11.egg (from tldextract->-r requirements.txt (line 1)) (3.15.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages/charset_normalizer-3.3.2-py3.11-linux-x86_64.egg (from requests->-r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages/certifi-2024.7.4-py3.11.egg (from requests->-r requirements.txt (line 3)) (2024.7.4)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 254.5 kB/s eta 0:00:00
Installing collected packages: requests
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
Successfully installed requests-2.32.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

┌──(ma㉿Windows11)-[~/ghauri]
└─$ sudo python3 setup.py install
running install
/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating ghauri.egg-info
writing ghauri.egg-info/PKG-INFO
writing dependency_links to ghauri.egg-info/dependency_links.txt
writing entry points to ghauri.egg-info/entry_points.txt
writing requirements to ghauri.egg-info/requires.txt
writing top-level names to ghauri.egg-info/top_level.txt
writing manifest file 'ghauri.egg-info/SOURCES.txt'
reading manifest file 'ghauri.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'ghauri.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ghauri
copying ghauri/__init__.py -> build/lib/ghauri
copying ghauri/ghauri.py -> build/lib/ghauri
creating build/lib/ghauri/scripts
copying ghauri/scripts/__init__.py -> build/lib/ghauri/scripts
copying ghauri/scripts/ghauri.py -> build/lib/ghauri/scripts
creating build/lib/ghauri/logger
copying ghauri/logger/colored_logger.py -> build/lib/ghauri/logger
copying ghauri/logger/__init__.py -> build/lib/ghauri/logger
creating build/lib/ghauri/core
copying ghauri/core/request.py -> build/lib/ghauri/core
copying ghauri/core/update.py -> build/lib/ghauri/core
copying ghauri/core/__init__.py -> build/lib/ghauri/core
copying ghauri/core/inject.py -> build/lib/ghauri/core
copying ghauri/core/extract.py -> build/lib/ghauri/core
copying ghauri/core/tests.py -> build/lib/ghauri/core
creating build/lib/ghauri/dbms
copying ghauri/dbms/fingerprint.py -> build/lib/ghauri/dbms
copying ghauri/dbms/__init__.py -> build/lib/ghauri/dbms
creating build/lib/ghauri/extractor
copying ghauri/extractor/advance.py -> build/lib/ghauri/extractor
copying ghauri/extractor/__init__.py -> build/lib/ghauri/extractor
copying ghauri/extractor/common.py -> build/lib/ghauri/extractor
creating build/lib/ghauri/common
copying ghauri/common/prettytable.py -> build/lib/ghauri/common
copying ghauri/common/session.py -> build/lib/ghauri/common
copying ghauri/common/colors.py -> build/lib/ghauri/common
copying ghauri/common/config.py -> build/lib/ghauri/common
copying ghauri/common/__init__.py -> build/lib/ghauri/common
copying ghauri/common/payloads.py -> build/lib/ghauri/common
copying ghauri/common/utils.py -> build/lib/ghauri/common
copying ghauri/common/banner.py -> build/lib/ghauri/common
copying ghauri/common/lib.py -> build/lib/ghauri/common
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ghauri
creating build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/scripts/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/scripts/ghauri.py -> build/bdist.linux-x86_64/egg/ghauri/scripts
creating build/bdist.linux-x86_64/egg/ghauri/logger
copying build/lib/ghauri/logger/colored_logger.py -> build/bdist.linux-x86_64/egg/ghauri/logger
copying build/lib/ghauri/logger/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/logger
creating build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/request.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/update.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/inject.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/extract.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/tests.py -> build/bdist.linux-x86_64/egg/ghauri/core
creating build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/dbms/fingerprint.py -> build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/dbms/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/__init__.py -> build/bdist.linux-x86_64/egg/ghauri
copying build/lib/ghauri/ghauri.py -> build/bdist.linux-x86_64/egg/ghauri
creating build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/advance.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/common.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
creating build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/prettytable.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/session.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/colors.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/config.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/payloads.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/utils.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/banner.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/lib.py -> build/bdist.linux-x86_64/egg/ghauri/common
byte-compiling build/bdist.linux-x86_64/egg/ghauri/scripts/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/scripts/ghauri.py to ghauri.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/logger/colored_logger.py to colored_logger.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/logger/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/request.py to request.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/update.py to update.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/inject.py to inject.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/extract.py to extract.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/tests.py to tests.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/dbms/fingerprint.py to fingerprint.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/dbms/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/ghauri.py to ghauri.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/advance.py to advance.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/common.py to common.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/prettytable.py to prettytable.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/session.py to session.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/colors.py to colors.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/config.py to config.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/payloads.py to payloads.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/utils.py to utils.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/banner.py to banner.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/lib.py to lib.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/ghauri-1.3.5-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ghauri-1.3.5-py3.11.egg
creating /usr/local/lib/python3.11/dist-packages/ghauri-1.3.5-py3.11.egg
Extracting ghauri-1.3.5-py3.11.egg to /usr/local/lib/python3.11/dist-packages
Adding ghauri 1.3.5 to easy-install.pth file
Installing ghauri script to /usr/local/bin

Installed /usr/local/lib/python3.11/dist-packages/ghauri-1.3.5-py3.11.egg
Processing dependencies for ghauri==1.3.5
Searching for chardet==5.2.0
Best match: chardet 5.2.0
Processing chardet-5.2.0-py3.11.egg
Adding chardet 5.2.0 to easy-install.pth file
detected new path './ghauri-1.3.5-py3.11.egg'
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.11/dist-packages/chardet-5.2.0-py3.11.egg
Searching for requests==2.32.3
Best match: requests 2.32.3
Adding requests 2.32.3 to easy-install.pth file

Using /usr/local/lib/python3.11/dist-packages
Searching for colorama==0.4.6
Best match: colorama 0.4.6
Adding colorama 0.4.6 to easy-install.pth file

Using /usr/local/lib/python3.11/dist-packages
Searching for tldextract==5.1.2
Best match: tldextract 5.1.2
Processing tldextract-5.1.2-py3.11.egg
Adding tldextract 5.1.2 to easy-install.pth file
Installing tldextract script to /usr/local/bin

Using /usr/local/lib/python3.11/dist-packages/tldextract-5.1.2-py3.11.egg
Searching for certifi==2024.7.4
Best match: certifi 2024.7.4
Processing certifi-2024.7.4-py3.11.egg
Adding certifi 2024.7.4 to easy-install.pth file

Using /usr/local/lib/python3.11/dist-packages/certifi-2024.7.4-py3.11.egg
Searching for urllib3==1.26.18
Best match: urllib3 1.26.18
Adding urllib3 1.26.18 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for idna==3.7
Best match: idna 3.7
Processing idna-3.7-py3.11.egg
Adding idna 3.7 to easy-install.pth file

Using /usr/local/lib/python3.11/dist-packages/idna-3.7-py3.11.egg
Searching for charset-normalizer==3.3.2
Best match: charset-normalizer 3.3.2
Processing charset_normalizer-3.3.2-py3.11-linux-x86_64.egg
Adding charset-normalizer 3.3.2 to easy-install.pth file
Installing normalizer script to /usr/local/bin

Using /usr/local/lib/python3.11/dist-packages/charset_normalizer-3.3.2-py3.11-linux-x86_64.egg
Searching for filelock==3.15.4
Best match: filelock 3.15.4
Processing filelock-3.15.4-py3.11.egg
Adding filelock 3.15.4 to easy-install.pth file

Using /usr/local/lib/python3.11/dist-packages/filelock-3.15.4-py3.11.egg
Searching for requests-file==2.1.0
Best match: requests-file 2.1.0
Processing requests_file-2.1.0-py3.11.egg
Adding requests-file 2.1.0 to easy-install.pth file

Using /usr/local/lib/python3.11/dist-packages/requests_file-2.1.0-py3.11.egg
Finished processing dependencies for ghauri==1.3.5

┌──(ma㉿Windows11)-[~/ghauri]
└─$ ghauri -h
Traceback (most recent call last):
  File "/home/ma/ghauri/ghauri/ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
  File "/home/ma/ghauri/ghauri/ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
ModuleNotFoundError: No module named 'ghauri.common'; 'ghauri' is not a package

┌──(ma㉿Windows11)-[~/ghauri]
└─$ ls
build  dist  ghauri  ghauri.egg-info  LICENSE  README.md  requirements.txt  setup.py

┌──(ma㉿Windows11)-[~/ghauri]
└─$ pwd
/home/ma/ghauri

┌──(ma㉿Windows11)-[~/ghauri]
└─$ ls
build  dist  ghauri  ghauri.egg-info  LICENSE  README.md  requirements.txt  setup.py

┌──(ma㉿Windows11)-[~/ghauri]
└─$ sudo python3 -m pip install -e .
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/ratelimit-2.2.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/dicttoxml-1.7.16-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/requests_file-2.1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/idna-3.7-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/ghauri-1.3.5-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/tldextract-5.1.2-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/certifi-2024.7.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/chardet-5.2.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/filelock-3.15.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/charset_normalizer-3.3.2-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/arjun-2.2.6-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Obtaining file:///home/ma/ghauri
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tldextract in /usr/local/lib/python3.11/dist-packages/tldextract-5.1.2-py3.11.egg (from ghauri==1.3.5) (5.1.2)
Requirement already satisfied: colorama in /usr/local/lib/python3.11/dist-packages (from ghauri==1.3.5) (0.4.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from ghauri==1.3.5) (2.32.3)
Requirement already satisfied: chardet in /usr/local/lib/python3.11/dist-packages/chardet-5.2.0-py3.11.egg (from ghauri==1.3.5) (5.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages/charset_normalizer-3.3.2-py3.11-linux-x86_64.egg (from requests->ghauri==1.3.5) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages/idna-3.7-py3.11.egg (from requests->ghauri==1.3.5) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->ghauri==1.3.5) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages/certifi-2024.7.4-py3.11.egg (from requests->ghauri==1.3.5) (2024.7.4)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.11/dist-packages/requests_file-2.1.0-py3.11.egg (from tldextract->ghauri==1.3.5) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.11/dist-packages/filelock-3.15.4-py3.11.egg (from tldextract->ghauri==1.3.5) (3.15.4)
Installing collected packages: ghauri
  Attempting uninstall: ghauri
    Found existing installation: ghauri 1.3.5
    Uninstalling ghauri-1.3.5:
      Successfully uninstalled ghauri-1.3.5
  Running setup.py develop for ghauri
Successfully installed ghauri-1.3.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

┌──(ma㉿Windows11)-[~/ghauri]
└─$ ls
build  dist  ghauri  ghauri.egg-info  LICENSE  README.md  requirements.txt  setup.py

┌──(ma㉿Windows11)-[~/ghauri]
└─$ pwd
/home/ma/ghauri

┌──(ma㉿Windows11)-[~/ghauri]
└─$ ghauri -h
Traceback (most recent call last):
  File "/home/ma/ghauri/ghauri/ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
  File "/home/ma/ghauri/ghauri/ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
ModuleNotFoundError: No module named 'ghauri.common'; 'ghauri' is not a package

┌──(ma㉿Windows11)-[~/ghauri]
└─$

**Comment by Bornunique911** [comment]
Did you use the following installation guideline or the steps mentioned in the Installation section itself?
https://github.com/r0oth3x49/ghauri/issues/119#issuecomment-1873049386

**Comment by a1k-ghaz1** [comment]
Yes. I tried all steps. Thanks

**Comment by r0oth3x49** [comment]
You must be using multiple installation of python. Try with admin or root to install. It should fix the issue at least this is what I have faced and fixed this way

**Comment by a1k-ghaz1** [comment]
I am using SQLMAP and many other Python-coded tools, but I have never seen an error like this one. No problem 😊 I will start using SQLMAP again by adding XOR time-based SQLi payloads in the XML config file. You can close this thread now. I know it won't run now even if I use sudo or root methods, but nothing is working now.
