### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by charis3306** [r0oth3x49/ghauri#166]
**Describe the bug**
Sqli-labs vulnerability shooting range cannot be detected.

![QQ_1722445551619](https://github.com/user-attachments/assets/e5ba5886-46fb-4ed6-980b-aeec5969d160)

use sqlmap

![QQ_1722445622787](https://github.com/user-attachments/assets/2fd5bd39-e730-4b79-a1ec-883ea926303e)

**Comment by r0oth3x49** [comment]
Try passing burp proxy and see whats going on why the URL is not responding to ghauri requests. Will check the labs if it's free otherwise you can use both tools sqlmap and ghauri, ghauri should work fine on  real-time env
