### ISSUE TITLE
ghauri can't run -r command,but ghauri can run --help command,What's the situation, boss!

### ISSUE THREAD

**Issue by geniusyutong** [r0oth3x49/ghauri#18]
The error is NameError: name 'v' is not defined
![image](https://user-images.githubusercontent.com/72134728/195232588-3fa9701a-699e-45ee-a053-b9b434e300d6.png)

**Comment by r0oth3x49** [comment]
would be great if you can just share the post json data as this json parsing still needs some fixing, so i might just need the json post data you are providing within your request file.

**Comment by r0oth3x49** [comment]
try with the latest version, if you still face the issue let me know.

**Comment by geniusyutong** [comment]
I'm sorry,Because this is customer data, Sensitive data involved，so I cannot provide json data,Thank you for your reply.
.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r0oth3x49/ghauri"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [r0oth3x49/ghauri] ghauri can't run -r command,but ghauri can run --help command,What's the situation, boss! (Issue #18)





 
try with the latest version, if you still face the issue let me know.

**Comment by r0oth3x49** [comment]
you can make a dummy one i 'm not saying to provide actual post data, i just want to take a look at the structure of json data.
example you can remove all the information just the structure and the point where you are trying to inject.

exmaple:

 json data: `{"name": "john", "roles": ["admin", "etc"]}`
 you can replace the actual fields key value with.
 json data: `{"key": "value", "key": ["value1", "value2", "value3INJECTING_HERE"]}`
 
 Still if you don't want to do this i will have to close this issue .
