### ISSUE TITLE
Unable to retrive database

### ISSUE THREAD

**Issue by Krafi1281** [r0oth3x49/ghauri#181]
Ghauri couldn't determine the number if character(s) in length query                   [15:07:25] [WARNING] it was not possible to extract query output length for the SQL query provided.

Please do something for that. I often get it.

**Comment by 0xAkarii** [comment]
I've the same issues here :
[DEBUG] Ghauri couldn't determine the number if character(s) in length query
[10:22:24] [WARNING] it was not possible to extract query output length for the SQL query provided.

**Comment by r0oth3x49** [comment]
Duplicate of #182
