### ISSUE TITLE
data dump

### ISSUE THREAD

**Issue by xcypher78** [r0oth3x49/ghauri#182]
sqlmap and JSQL give dump data and ghauri not

[23:08:48] [WARNING] it was not possible to extract query output length for the SQL query provided.
[23:08:48] [CRITICAL] Ghauri was not able identify payload for table dump, try manually.

**Comment by r0oth3x49** [comment]
@xcypher78 did you clearly read the error what it is saying? Try manually that means either firewall is blocking or ghauri don't have any query to do that for you.  Next time I will not respond to such issues and will directly close. 

If it says try manually then try manually this is not an issue but a suggestion from ghauri that you should try manually if you can find some sort of bypass or something then try using --sql-shell to pass your query to ghauri

**Comment by r0oth3x49** [comment]
@xcypher78 did you clearly read the error what it is saying? Try manually that means either firewall is blocking or ghauri don't have any query to do that for you.  Next time I will not respond to such issues and will directly close. 

If it says try manually then try manually this is not an issue but a suggestion from ghauri that you should try manually if you can find some sort of bypass or something then try using --sql-shell to pass your query to ghauri
