### ISSUE TITLE
error install 

### ISSUE THREAD

**Issue by anubi5egypt** [r0oth3x49/ghauri#19]
1 : ┌─[✗]─[anubi5@parrot]─[~/Downloads/ghauri-main]
└──╼ $sudo python3 setup.py install 
[sudo] password for anubi5: 
running install
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.14.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
creating ghauri.egg-info
writing ghauri.egg-info/PKG-INFO
writing dependency_links to ghauri.egg-info/dependency_links.txt
writing entry points to ghauri.egg-info/entry_points.txt
writing requirements to ghauri.egg-info/requires.txt
writing top-level names to ghauri.egg-info/top_level.txt
writing manifest file 'ghauri.egg-info/SOURCES.txt'
reading manifest file 'ghauri.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'ghauri.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ghauri
copying ghauri/__init__.py -> build/lib/ghauri
copying ghauri/ghauri.py -> build/lib/ghauri
creating build/lib/ghauri/common
copying ghauri/common/__init__.py -> build/lib/ghauri/common
copying ghauri/common/banner.py -> build/lib/ghauri/common
copying ghauri/common/colors.py -> build/lib/ghauri/common
copying ghauri/common/config.py -> build/lib/ghauri/common
copying ghauri/common/lib.py -> build/lib/ghauri/common
copying ghauri/common/payloads.py -> build/lib/ghauri/common
copying ghauri/common/prettytable.py -> build/lib/ghauri/common
copying ghauri/common/session.py -> build/lib/ghauri/common
copying ghauri/common/utils.py -> build/lib/ghauri/common
creating build/lib/ghauri/core
copying ghauri/core/__init__.py -> build/lib/ghauri/core
copying ghauri/core/extract.py -> build/lib/ghauri/core
copying ghauri/core/inject.py -> build/lib/ghauri/core
copying ghauri/core/request.py -> build/lib/ghauri/core
copying ghauri/core/tests.py -> build/lib/ghauri/core
creating build/lib/ghauri/dbms
copying ghauri/dbms/__init__.py -> build/lib/ghauri/dbms
copying ghauri/dbms/fingerprint.py -> build/lib/ghauri/dbms
creating build/lib/ghauri/extractor
copying ghauri/extractor/__init__.py -> build/lib/ghauri/extractor
copying ghauri/extractor/advance.py -> build/lib/ghauri/extractor
copying ghauri/extractor/common.py -> build/lib/ghauri/extractor
creating build/lib/ghauri/logger
copying ghauri/logger/__init__.py -> build/lib/ghauri/logger
copying ghauri/logger/colored_logger.py -> build/lib/ghauri/logger
creating build/lib/ghauri/scripts
copying ghauri/scripts/__init__.py -> build/lib/ghauri/scripts
copying ghauri/scripts/ghauri.py -> build/lib/ghauri/scripts
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ghauri
copying build/lib/ghauri/__init__.py -> build/bdist.linux-x86_64/egg/ghauri
copying build/lib/ghauri/ghauri.py -> build/bdist.linux-x86_64/egg/ghauri
creating build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/banner.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/colors.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/config.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/lib.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/payloads.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/prettytable.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/session.py -> build/bdist.linux-x86_64/egg/ghauri/common
copying build/lib/ghauri/common/utils.py -> build/bdist.linux-x86_64/egg/ghauri/common
creating build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/extract.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/inject.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/request.py -> build/bdist.linux-x86_64/egg/ghauri/core
copying build/lib/ghauri/core/tests.py -> build/bdist.linux-x86_64/egg/ghauri/core
creating build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/dbms/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/dbms
copying build/lib/ghauri/dbms/fingerprint.py -> build/bdist.linux-x86_64/egg/ghauri/dbms
creating build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/advance.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
copying build/lib/ghauri/extractor/common.py -> build/bdist.linux-x86_64/egg/ghauri/extractor
creating build/bdist.linux-x86_64/egg/ghauri/logger
copying build/lib/ghauri/logger/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/logger
copying build/lib/ghauri/logger/colored_logger.py -> build/bdist.linux-x86_64/egg/ghauri/logger
creating build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/scripts/__init__.py -> build/bdist.linux-x86_64/egg/ghauri/scripts
copying build/lib/ghauri/scripts/ghauri.py -> build/bdist.linux-x86_64/egg/ghauri/scripts
byte-compiling build/bdist.linux-x86_64/egg/ghauri/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/ghauri.py to ghauri.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/banner.py to banner.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/colors.py to colors.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/config.py to config.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/lib.py to lib.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/payloads.py to payloads.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/prettytable.py to prettytable.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/session.py to session.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/common/utils.py to utils.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/extract.py to extract.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/inject.py to inject.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/request.py to request.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/core/tests.py to tests.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/dbms/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/dbms/fingerprint.py to fingerprint.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/advance.py to advance.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/extractor/common.py to common.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/logger/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/logger/colored_logger.py to colored_logger.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/scripts/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/ghauri/scripts/ghauri.py to ghauri.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ghauri.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/ghauri-1.0.7-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ghauri-1.0.7-py3.9.egg
removing '/usr/lib/python3.9/site-packages/ghauri-1.0.7-py3.9.egg' (and everything under it)
creating /usr/lib/python3.9/site-packages/ghauri-1.0.7-py3.9.egg
Extracting ghauri-1.0.7-py3.9.egg to /usr/lib/python3.9/site-packages
ghauri 1.0.7 is already the active version in easy-install.pth
Installing ghauri script to /usr/bin

Installed /usr/lib/python3.9/site-packages/ghauri-1.0.7-py3.9.egg
Processing dependencies for ghauri==1.0.7
Searching for chardet==5.0.0
Best match: chardet 5.0.0
Adding chardet 5.0.0 to easy-install.pth file
Installing chardetect script to /usr/bin

Using /usr/local/lib/python3.9/dist-packages
Searching for requests==2.28.1
Best match: requests 2.28.1
Adding requests 2.28.1 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for colorama==0.4.5
Best match: colorama 0.4.5
Adding colorama 0.4.5 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for tldextract==3.4.0
Best match: tldextract 3.4.0
Adding tldextract 3.4.0 to easy-install.pth file
Installing tldextract script to /usr/bin

Using /usr/local/lib/python3.9/dist-packages
Searching for certifi==2022.6.15
Best match: certifi 2022.6.15
Adding certifi 2022.6.15 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for urllib3==1.26.5
Best match: urllib3 1.26.5
Adding urllib3 1.26.5 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for charset-normalizer==2.1.0
Best match: charset-normalizer 2.1.0
Adding charset-normalizer 2.1.0 to easy-install.pth file
Installing normalizer script to /usr/bin

Using /usr/local/lib/python3.9/dist-packages
Searching for filelock==3.7.1
Best match: filelock 3.7.1
Adding filelock 3.7.1 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for requests-file==1.5.1
Best match: requests-file 1.5.1
Adding requests-file 1.5.1 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Finished processing dependencies for ghauri==1.0.7

![2022-10-16_14-20_1](https://user-images.githubusercontent.com/42506882/196035242-9eb6b5d7-4f76-4316-ab8e-e6133604a9e2.png)

**Comment by anubi5egypt** [comment]
![2022-10-16_14-20](https://user-images.githubusercontent.com/42506882/196035270-393a582b-4857-4839-90a9-28a9af829ee0.png)

**Comment by r0oth3x49** [comment]
I will check this on parrot os and get back to you

**Comment by r0oth3x49** [comment]
i can easily run ghauri on parrot os what i did is:
- downloaded latest iso image from official web.
- installed in vm.
- clone latest version of ghauri.
- installed `sudo apt install python-is-python3`
- installed ghauri using `python -m pip install -e . --upgrade`
- then ran the ghauri from both users/ root and normal user and it worked perfectly fine.
- see the images below.
![Screenshot at 2022-10-18 08-16-28](https://user-images.githubusercontent.com/11024397/196375770-eb5ec635-6e05-4de1-be00-197b4ef63950.png)
![Screenshot at 2022-10-18 08-17-21](https://user-images.githubusercontent.com/11024397/196375779-d79a8e2c-f6eb-4fbc-b915-18de3f6486c1.png)

**Comment by 2ptt** [comment]
I am also facing the same problem.

PS C:\Users\msh\Desktop\tools\ghauri\ghauri> python.exe .\ghauri.py
Traceback (most recent call last):
  File "C:\Users\msh\Desktop\tools\ghauri\ghauri\ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
  File "C:\Users\msh\Desktop\tools\ghauri\ghauri\ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
ModuleNotFoundError: No module named 'ghauri.common'; 'ghauri' is not a package
PS C:\Users\msh\Desktop\tools\ghauri\ghauri>
