### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by Frido-Cpp** [r0oth3x49/ghauri#22]
I installed ghauri on my Windows Cmd exactly as in the README, but on execution, It is not found.

C:\Users\Uzer\Desktop\ghauri>ghauri --help
'ghauri' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Uzer\Desktop\ghauri>

**Comment by r0oth3x49** [comment]
it works fine i cannot reproduce the issue you are facing.
![Capture](https://user-images.githubusercontent.com/11024397/201326444-30c64bf6-bf1e-4bc0-81c0-f314e683ef9e.PNG)
