### ISSUE TITLE
Add threads 

### ISSUE THREAD

**Issue by smurfrules33** [r0oth3x49/ghauri#24]
It would be better if you added a multi-thread future 

Cheers!

**Comment by r0oth3x49** [comment]
@smurfrules33 added multi-thread support currently just for boolean based blind injections only. this is testing phase and ghauri for now will only allow max threads upto 4.
![threads](https://user-images.githubusercontent.com/11024397/209432070-a3f3f653-f2a8-4680-9a0f-c9630eaf64c7.PNG)
