### ISSUE TITLE
Cannot detect * mark properly in JSON post body , json body is not well handled.

### ISSUE THREAD

**Issue by xkoll1** [r0oth3x49/ghauri#26]
If I have multiple key value pairs in json post body like {"name":"test", "id":"1"}
and change it to {"name":"test", "id":"*"}   ----> it does not detect the * mark and it keeps on automatically testing the body. Also sometimes it does not travel through the JSON well.
I tested the same POST JSON body in sqlmap but it went well there

**Comment by r0oth3x49** [comment]
Will check this ASAP. There are issues that I know about processing json and hopefully it will be fixed soon
