### ISSUE TITLE
No module named 'ghauri.common'; 'ghauri' is not a package

### ISSUE THREAD

**Issue by w4h4z** [r0oth3x49/ghauri#29]
**Describe the bug**
I found this bug when I try to first running ghauri, I already installed the requirements.
Any help? thank you

![Screenshot 2022-11-28 210127](https://user-images.githubusercontent.com/21325741/204296562-2f6ee6a2-abe0-42a8-9d74-5941786d176e.png)

**Comment by r0oth3x49** [comment]
dup of #28 , i already have described the solution there. you should be installing it instead of running the *ghauri.py* file. follow installation guide

**Comment by w4h4z** [comment]
I already follow the installation guide, but there is some error, any help?

![image](https://user-images.githubusercontent.com/21325741/204526585-3d2d285d-5c78-4622-b346-72cd0a8d7336.png)
