### ISSUE TITLE
Does ghauri run on Windows?

### ISSUE THREAD

**Issue by mjulda** [r0oth3x49/ghauri#30]
How to run it on Windows?

**Comment by r0oth3x49** [comment]
Yes. This is cross platform you can install it like any other python module.

**Comment by mjulda** [comment]
> Yes. This is cross platform you can install it like any other python module.



> Yes. This is cross platform you can install it like any other python module.

I've done various commands to install, but still can't.
python3 -m pip install --upgrade -r requirements. txt
python3 setup.py
python3 -m pip install -e .
"python setup.py install --user"

Can you help me?

**Comment by r0oth3x49** [comment]
python is installed and added to env variables right? if so it should work as i have tested it on windows OS
