### ISSUE TITLE
giving error when data is to be fetched from database

### ISSUE THREAD

**Issue by dheeraj750** [r0oth3x49/ghauri#34]
hey
 ghauri tool is giving error when data is to be fetched from database then this error is coming .

<img width="694" alt="2022-12-20 08_50_46-AWS CloudShell - Brave" src="https://user-images.githubusercontent.com/83754869/208577477-b107fb73-9aab-432e-b89e-e1265f2ecf51.png">

**Comment by r0oth3x49** [comment]
that is because i didn't added further payloads for Microsoft Access database will handle this exception.
