### ISSUE TITLE
This is literally a SQLMap fork

### ISSUE THREAD

**Issue by ItsViolet** [r0oth3x49/ghauri#37]
**Describe the bug**

**To Reproduce**
1. clone the latest version
2. installed using following command ```....```
3. Run the following command ```...```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu/Windows/MacOS]
 - Ghauri version which is causing the error (should be latest) [e.g. 1.0.1]
 - Type of SQL injection which cause the error: [e.g. boolean/time/error based]
 - Phase where error occur: [e.g. detection/(db(s)/banner/user/table/column/data) exfiltration phase]

**Additional context**

**Comment by ItsViolet** [comment]
Just use your common sense. What took SQLMap developers continuous work from 2006 to 2023 was built by this guy in like a month? And seriously, how'd you get a whole lot of code which suspiciously looks like SQLMap in your 2nd goddamn commit??

**Comment by ItsViolet** [comment]
And why do you only update payloads and shit instead of actual code since your 2nd commit? Cannot write code, I presume?

**Comment by ItsViolet** [comment]
SQLMap aside, you also copied your own goddamn repo. https://github.com/r0oth3x49/Xpath seriously?
and they both are sqlmap copies.

**Comment by ItsViolet** [comment]
How far would you go just for fancy internet stars?

**Comment by r0oth3x49** [comment]
Don't use this go do your shit some where else.

**Comment by r0oth3x49** [comment]
> And why do you only update payloads and shit instead of actual code since your 2nd commit? Cannot write code, I presume?

This the dumbest comment ever I have seen. I don't know code I am still copying sqlmap. You want to learn Python I can teach you you dumbo.

**Comment by r0oth3x49** [comment]
> Just use your common sense. What took SQLMap developers continuous work from 2006 to 2023 was built by this guy in like a month? And seriously, how'd you get a whole lot of code which suspiciously looks like SQLMap in your 2nd goddamn commit??

Really man were you there sitting next to me when I was coding this in a whole month right. BTW who is forcing you to use this go do your shits some where else.

**Comment by r0oth3x49** [comment]
BTW I will continue to update like I am doing right now I don't care about people like you who just come and shit everywhere.

**Comment by r0oth3x49** [comment]
Users give a star when they find it useful I am not forcing them too. BTW you better focus on learning Kotlin/JS coding stuff like this is not for kid like you.

**Comment by ItsViolet** [comment]
Yo what I am a senior lead developer with a masters in software development from University of Colorado.

**Comment by r0oth3x49** [comment]
Lol then above convo is expected from you because you are a developer.

**Comment by phpmac** [comment]
I was wondering what are the better advantages over sqlmap? Just saw this
