### ISSUE TITLE
Error install in latest version

### ISSUE THREAD

**Issue by zinminphyo0** [r0oth3x49/ghauri#38]
I installed the latest version, but I got this error

![2023-01-19_23-28](https://user-images.githubusercontent.com/74085414/213617552-77a0c90c-1a56-49b5-863d-062998f39b42.png)

**Comment by r0oth3x49** [comment]
Which OS you are using I will try to reproduce on that?

**Comment by zinminphyo0** [comment]
thank you for your replay, i am install on VPS(ubuntu)

**Comment by r0oth3x49** [comment]
@zinminphyo0 i am using VPS(ubuntu) and it works fine for me. check the images below.
![check01](https://user-images.githubusercontent.com/11024397/216545592-b2e15764-69e9-44d0-9dc9-55c000702020.PNG)

![check](https://user-images.githubusercontent.com/11024397/216545579-09b88531-3020-45c0-be98-8df626db89bf.PNG)

**Comment by zinminphyo0** [comment]
it's working now, problem from my VPS, Thank you so much
![2023-02-03_17-11](https://user-images.githubusercontent.com/74085414/216720828-2766f27c-28b6-48f6-b47c-b46f39edaad5.png)

**Comment by counterterrorismp** [comment]
hello can you please tell me what you did with your vps, Im facing this as well on my vps, thanks

**Comment by r0oth3x49** [comment]
@counterterrorismp are you following proper installation steps and one more thing is that ghauri will only work with python >= 3.6
