### ISSUE TITLE
a website  Ghauri was not able to establish connection - soup/xml based post data support

### ISSUE THREAD

**Issue by Iceqaq** [r0oth3x49/ghauri#47]
why？ This website can be accessed
![image](https://user-images.githubusercontent.com/43596990/225888935-0c5ee2fe-9e58-49b7-baba-e3dde0de6fa0.png)

![image](https://user-images.githubusercontent.com/43596990/225889207-60f1f447-06f0-48f7-b5db-1ca0d2cc5b2f.png)

![image](https://user-images.githubusercontent.com/43596990/225889311-d34430e6-1d9d-4f71-babf-85830cd7b872.png)

**Comment by r0oth3x49** [comment]
@Iceqaq currently ghauri doesn't support xml/soup based post requests will add this feature in a coming version.

**Comment by r0oth3x49** [comment]
For connection issue you can try using burp proxy it should work but again soup/xml based post data processing is not added yet so ghauri will not be able to identify insertion points properly
