### ISSUE TITLE
need help!!

### ISSUE THREAD

**Issue by blackcodersec** [r0oth3x49/ghauri#48]
First of all thanks for your ghauri project.

Ghauri detected a vulnerable parameter. But after that ghauri does not fetching any kind of information like, db info, hostname, current-user.

could you help me please. this is my first sqli.

![image](https://user-images.githubusercontent.com/72689232/228320844-119e99d3-5bc5-4eaa-aa97-1308f47ddb79.png)

**Comment by r0oth3x49** [comment]
Can you share a verbose output with -v 5 either here or on my mail: nasir251292@gmail.com?

**Comment by blackcodersec** [comment]
thanks for help :)
