### ISSUE TITLE
Time based payload sleep times inconsistent

### ISSUE THREAD

**Issue by conditi0ns** [r0oth3x49/ghauri#54]
Default sleep time for time based payloads appears to be 9 seconds from observing the request traffic even though it states it's set to 5 as a default. Attempting to force it via --time-sec 5 and now the request payloads are sending sleep requests for 7 seconds? Another case, setting --time-sec to 6 and the payloads are sending sleep times of 9. Even more odd, any value > 10 on --time-sec seems to be sent correctly. Not sure what's going on here.

**Comment by conditi0ns** [comment]
This seems to be from tests.py where if on a good internet connection it will select a random value between 5 and 9. I'm guessing this is for WAF evasion.

Otherwise if the connection is poor it will set the value to 10 and increment by 1 until it stabilizes.

This would explain the behavior I'm seeing now so I'll close this one out.

```
# in case of very slow internet users we will consider timesec value for testing and it should be >= 10 otherwise with good internet we are good to consider random sleep value
    sleep_time = timesec if timesec >= 10 else random.randint(5, 9)
```

**Comment by r0oth3x49** [comment]
@conditi0ns the set value time-sec switch works when the injection is confirmed and we are in phase of extraction after confirming the SQLi, In testing phase ghauri doesn't consider time-sec value.
