### ISSUE TITLE
ghauri will not be able to extract data!!

### ISSUE THREAD

**Issue by blackcodersec** [r0oth3x49/ghauri#55]
cloud you see this error?
![image](https://user-images.githubusercontent.com/72689232/230797871-a769d8f3-5e9a-444e-89ae-8d0740ad78fd.png)

**Comment by r0oth3x49** [comment]
Try --fetch-using=between/in/equal/binary one by one. If still shows this error that means you need to do it manually or you can send the request file on my mail: nasir251292@gmail.com for testing

**Comment by r0oth3x49** [comment]
Hopefully above switches helped you. Closing the issue as I don't see anything else to discuss.
