### ISSUE TITLE
Adding UTF-8 

### ISSUE THREAD

**Issue by 1br00** [r0oth3x49/ghauri#57]
Hello, can you add utf-8 encoding
because when i dump data that have (č,ć,š,đ) it will not be visible, and it says invalid character detected in the ghauri..

2. Can you add like in sqlmap -m option to add .txt list of urls to test?
3. sqlmap have option --batch=list of payloads, can you that too?  to import manual our payloads which we want

p.s You are better than whole entire then from sqlmap, u doing great work.
Ghauri is more popular now than sqlmap

**Comment by 1br00** [comment]
And I'am waiting Ghauri for BurpSuite plugin to buy😊😊

**Comment by r0oth3x49** [comment]
Hey @1br00 , I will the UTF-8 thing but need a target to test if you have or know any example targets returns such chars in data you can share that on my email : nasir251292@gmail.com. 

Regarding -m switch its already in queue and will be implemented in up coming updates. Will check the --batch switch too

**Comment by r0oth3x49** [comment]
No response on this issue and I don't have a target so I will include this once I have a target to test against. For now closing the issue
