### ISSUE TITLE
URI injection

### ISSUE THREAD

**Issue by arrm001** [r0oth3x49/ghauri#61]
Hello,

When I try to do URI injection your tool fails automatically. Would it be possible to add this feature to your tool?

For example, sqlmap gives you the option to choose for URI injection.

Thanks.
![image](https://user-images.githubusercontent.com/131351568/233320284-c043ff44-57c1-41d2-995c-66e8011aba98.png)

**Comment by r0oth3x49** [comment]
For now you can try inserting custom injection marker within the uri it should scan
