### ISSUE TITLE
error in install

### ISSUE THREAD

**Issue by netwons** [r0oth3x49/ghauri#62]
I installed it in Linux with these commands, but it gives an error
**pip install -r requirements.txt
sudo python3 setup.py install**

link [https://pasteboard.co/OaIGQmkObEWs.png](https://pasteboard.co/OaIGQmkObEWs.png)

**Comment by Lulztigre** [comment]
I have this same issue as well

**Comment by r0oth3x49** [comment]
Works fine for me can't reproduce.

**Comment by Lulztigre** [comment]
![Screenshot_20230506_202800](https://user-images.githubusercontent.com/37852930/236643195-6e9dd79c-90d2-4351-ab67-a0973edb522f.png)
