### ISSUE TITLE
This is SQL map....

### ISSUE THREAD

**Issue by AnubisTwine** [r0oth3x49/ghauri#7]
Why have you cloned SQL map and calling it something else?? What have you done to modify or improve the software code??

**Comment by r0oth3x49** [comment]
Can you prove this sqlmap clone? If not then don't just create issues like a crazy man. Just checked the source and let me know how this is clone of sqlmap? If you don't want to use this software that's fine just use the sqlmap but don't create such nonsense issues to waste my time

**Comment by r0oth3x49** [comment]
Reopen the issue if you can prove this is a clone

**Comment by AnubisTwine** [comment]
Look at SQL map and you will see yourself. You must know this already 🤣. I
don't need your tools when I have hundreds of professional tools myself. I
have reported this repo.

**Comment by r0oth3x49** [comment]
Good luck. Your answer speak of yourself how dumb you are by just looking at the output and saying its copy.

**Comment by oldkingcone** [comment]
this is a direct clone of sqlmap.

**Comment by ItsViolet** [comment]
Just use your common sense. What took SQLMap developers continuous work from 2006 to 2023 was built by this guy in like a month? And seriously, how'd you get a whole lot of code which suspiciously looks like SQLMap in _your 2nd goddamn commit??_

**Comment by 1nf1n7y** [comment]
this is a clone of sqlmap
