### ISSUE TITLE
Ms access

### ISSUE THREAD

**Issue by xcypher78** [r0oth3x49/ghauri#73]
[WARNING] ghauri currently only supports DBMS fingerprint payloads for Microsoft Access, exfiltration will be added soon.....

**Comment by r0oth3x49** [comment]
@xcypher78 I don't have any target vuln to msaccess db that is why you are facing this issue if you have one you can share on my mail: nasir251292@gmail.com

**Comment by r0oth3x49** [comment]
Sure np, right now I don't have any target or lab setup vuln to msaccess so I cannot implement this will see in future updates, closing this issue.

**Comment by xcypher78** [comment]
thanks

**Comment by 0xPugal** [comment]
```
[05:31:58] [WARNING] ghauri currently only supports DBMS fingerprint payloads for Microsoft Access, exfiltration will be added soon```
