### ISSUE TITLE
Getting error while performing attack 

### ISSUE THREAD

**Issue by stish834** [r0oth3x49/ghauri#78]
![Screenshot from 2023-06-06 20-49-22](https://github.com/r0oth3x49/ghauri/assets/31948359/c0794fc4-a754-40db-96b7-a6cb7dfbb0ed)

**Comment by r0oth3x49** [comment]
@stish834 you would need to share the request file removing original target host so that I can take a look and fix because I cannot reproduce this.

**Comment by r0oth3x49** [comment]
no response on this so closing this issue as i need a request file to reproduce an fix the issue otherwise i cannot reproduce.
