### ISSUE TITLE
add a sussion fro testing diffrent pay loads 

### ISSUE THREAD

**Issue by imran-niaz** [r0oth3x49/ghauri#8]
Add area for input so user can test there own payloads . i have use this its part of Sqlmap. a quait SAME

**Comment by r0oth3x49** [comment]
you mean by `--sql-shell`?

**Comment by imran-niaz** [comment]
no different pay loads

**Comment by imran-niaz** [comment]
chmod 777 ghauri

**Comment by r0oth3x49** [comment]
Can you please be more specific I am not getting your point? What you actually want

**Comment by imran-niaz** [comment]
I wanna say that if  I have different payloads in txt { input locate  file pay loads }. For sql or others Db testing. So I can locate that and use for testing.   

It tack my own payloads and test for it   

Another examle that sqlmap –u xyz.com -I payloads.txt  

Output : “:” work show error 500 .  

Output {}  Not working weeor 403  

And etc

**Comment by r0oth3x49** [comment]
Will check this out.

**Comment by imran-niaz** [comment]
@r0oth3x49 this will help us ..
