### ISSUE TITLE
Tool is not able to read the parameter in the post request which is saved in the file

### ISSUE THREAD

**Issue by Jogissingh** [r0oth3x49/ghauri#80]
![image](https://github.com/r0oth3x49/ghauri/assets/91064136/a18b2fb3-fd43-42f0-9857-82c0b127fb95)

getting (no parameter(s) found for testing in the provided data (e.g. GET parameter 'id' in 'www.site.com/index.php?id=1') )
error when using the file to test the scenario.

[allocationaddress-data.txt](https://github.com/r0oth3x49/ghauri/files/11741720/allocationaddress-data.txt)

attaching the file for the same please look into this and please suggest if I am doing anything wrong.

And it is a request also can you provide a tutorial to test REST API both method get and post it will be very helpful.

**Comment by r0oth3x49** [comment]
@Jogissingh you are providing a wrong request file a valid request should look like:
```
POST /recovery/fos/allocation/address-data HTTP/1.1
HOST: redacted[.]com
Authenticationtoken: a720d029-3fa3-4a28-809f-5219efc58799
Referer: https://redacted[.]com/abc.html
Content-Type: application/json
Lang: en_in
Content-Length: 109
Accept-Encoding: gzip, deflate
User-Agent: okhttp/4.9.2


{"loan_id":["Online19"],"allocation_month":"2023-5-01","company_id":"b2d11f40-1337-4309-ab19-982e44f28675"}
```
