### ISSUE TITLE
Ghauri is not able to recognise parameters.

### ISSUE THREAD

**Issue by urakesh661** [r0oth3x49/ghauri#83]
Hi,

Thanks for creating this  tool!

I would like to bring your attention to below issue which I am facing:

Getting error on running command : ghauri -r /Users/rakesh/Documents/Project/Web/NodeGoat/request_benefits.txt

**Error:** 

[10:25:46] [INFO] parsing HTTP request from '/Users/rakesh/Documents/Project/Web/NodeGoat/request_benefits.txt'
[10:25:46] [CRITICAL] no parameter(s) found for testing in the provided data (e.g. GET parameter 'id' in 'www.site.com/index.php?id=1')

**Request:**

POST /benefits HTTP/1.1
Host: localhost:4000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0)
Gecko/20100101 Firefox/114.0
Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 36
Origin: http://localhost:4000
Connection: close
Referer: http://localhost:4000/benefits
Cookie:
connect.sid=s%3AYoTJiL8n06kgek1kzOIADp0FNS1QTP0S.Y%2BuJDaXHwSCr%2BZyVzRLUmnVQZcmdTjaerkYP4Y97gdE
Upgrade-Insecure-Requests: 1

userId=2&benefitStartDate=2030-01-10

Ghauri is not able to find the parameters from the request.

**Comment by r0oth3x49** [comment]
You are providing a wrong request format, check that your request has multiple new line separators within user-agent header and after accept header as well as cookie fix that and Ghauri should work fine. 

I would recommend instead of creating request on your own simply intercept it in burp and save to file everything should work fine. Fixing http request is not part of ghauri code you should provide a proper request instead. Do follow the recommendations

**Comment by r0oth3x49** [comment]
```
POST /benefits HTTP/1.1
Host: localhost:4000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,/;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 36
Origin: http://localhost:4000
Connection: close
Referer: http://localhost:4000/benefits
Cookie: connect.sid=s%3AYoTJiL8n06kgek1kzOIADp0FNS1QTP0S.Y%2BuJDaXHwSCr%2BZyVzRLUmnVQZcmdTjaerkYP4Y97gdE
Upgrade-Insecure-Requests: 1

userId=2&benefitStartDate=2030-01-10
```

Here is fixed version of your request try this

**Comment by urakesh661** [comment]
Thanks,it is working fine now.
