### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by subh-sinha** [r0oth3x49/ghauri#84]
Error when installing 
![ghauri](https://github.com/r0oth3x49/ghauri/assets/99028344/232d5d36-0c45-4c2c-9a57-082f97d2a72b)

**Comment by r0oth3x49** [comment]
Try installing using pip instead, I cannot reproduce the issue.

**Comment by subh-sinha** [comment]
> use this command `sudo python3 setup.py install`

Thanks It's Worked
