### ISSUE TITLE
 it appears that the character '>' is filtered by the back-end server. ghauri will based data retrieval on BETWEEN operator

### ISSUE THREAD

**Issue by ErrorMySQL** [r0oth3x49/ghauri#93]
how to use tamper in ghauri for bypass WAF ?? 

and i have problem whene i retreive data "[WARNING] invalid character detected, retrying.." and "it appears that the character '>' is filtered by the back-end server. ghauri will based data retrieval on BETWEEN operator" 

what sollution?

**Comment by r0oth3x49** [comment]
Ghauri don't have tamper support so no way to use tamper script. The warning you are facing is a handle to incorrect character so this is not an issue but a solution to avoid false characters. When > blocked by firewall it switches automatically to between and then assignment operator (=) to bypass firewall. 

So all in all what you are facing is not an issue but a handle to an issue and no tamper support as of yet. Will add support in near future but don't know the exact time line as I work on Ghauri in my free times.
