### ISSUE TITLE
When 403 (Forbidden), ghauri asks for user input (y/n) even when I have used --batch argument

### ISSUE THREAD

**Issue by Nishantbhagat57** [r0oth3x49/ghauri#98]
**Describe the bug**
When 403 (Forbidden), ghauri asks for user input (y/n) even when I have used --batch argument.

My command:
```ghauri -r req.txt --timeout 10 --threads 40 --level 3 --batch```

Ghauri Output:
![Screenshot 2023-09-15 222001](https://github.com/r0oth3x49/ghauri/assets/64642374/d82bdab1-bc1f-47cf-8eba-ad6d668ef3d5)

**Expected behavior**
```--batch             Never ask for user input, use the default behavior```

**Desktop:**
 - OS: [Debian]
 - Ghauri version: latest 1.2.4
 - Type of SQL injection which cause the error: [Default]

**Comment by r0oth3x49** [comment]
That is intentional behavior because usually it is firewall blocking requests so hammering it won't help either way until the bypass is there within  ghauri. So not a bug.

**Comment by Nishantbhagat57** [comment]
```--batch   Never ask for user input, use the default behavior```

@r0oth3x49 Well then there should be a default behaviour for that 403 Forbidden, that's "N" coz as you said "hammering it won't help" and you haven't added that default behaviour yet.

Actually it's breaking my automation where I am using 8 axiom instances parallely scanning urls using ghauri...If at somepoint the server responds with 403, then the whole automation will break as ghauri will be expecting an input (y/n) whereas it should have taken the default input as N itself and have stopped further scanning as I have already added --batch argument  :/

Well if you don't want to change anything then still you can add an option to select default behaviour (y/n) which can be used with --batch like this:

```ghauri -r req.txt --level 3 --default-behavior N --batch```

**Comment by Nishantbhagat57** [comment]
ping @r0oth3x49
